Backup include monitoring
Frachtwerk/ansible-role-docker pull request #6
Opened 2024-10-24 10:00 UTC by janitor-of-code

Deployed the db dump on a few hosts and expanded a few things:
- added ping to [healthchecks.io](https://healthchecks.io/docs/) for monitoring
- added `ignore_errors` on check_mode so i can actually use the check mode
- typos
- minor bugfixes

includes changes from merge #5

2024-10-25 07:51 UTC, tldev-de requested changes
nice! we added some minor suggestions, can you please have a look at these lines?

2024-10-25 07:51 UTC, tldev-de commented on templates/database_docker_backup.sh.j2
> +ping_body="[${SUM_OF_BACKUPS}x] $(tail -n 4 {{ docker_database_backup_path }}/last_run.txt)"
you can use `$CURRENT_DIR`, which is used generally in the script, instead of `{{ docker_database_backup_path }}`

2024-10-25 07:51 UTC, tldev-de commented on templates/database_docker_backup.sh.j2
> +ping_body="[${SUM_OF_BACKUPS}x] $(tail -n 4 {{ docker_database_backup_path }}/last_run.txt)"
`[${SUM_OF_BACKUPS}x]` please give some context here. for a user without knowing the script, it is unclear what [2x] means in the log. can we change this to `[${SUM_OF_BACKUPS} backups started]`. a line break below this line would be helpful as well! we think, you need to use `echo` whith piping into a var

2024-10-25 08:12 UTC, tldev-de commented on tasks/main.yml
> +  when: not ansible_check_mode
why are you using `not ansible_check_mode` here?

the [ansible docs](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html#attributes) say: 

> Can run in check_mode and return changed status prediction without modifying target, if not supported the action will be skipped.

2024-10-25 08:12 UTC, tldev-de commented on tasks/main.yml
> +  when: not ansible_check_mode
why are you using `not ansible_check_mode` here?

the [ansible docs](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/meta_module.html#attribute-check_mode) say: 

> While these actions don’t modify the targets directly they do change possible states of the target within the run

2025-01-27 13:47 UTC, lonjo approved these changes

2025-01-31 12:58 UTC, lonjo approved these changes

2025-01-31 13:10 UTC, merged